[versions]
kotlin = "2.0.21"
junit = "4.13.2"
pf4j = "3.12.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
pf4j = { group = "org.pf4j", name = "pf4j", version.ref = "pf4j" }

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

